---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/pcf-usage-tools
    tag: "latest"

inputs:
  - name: pipeline-scripts
  - name: report-time-range
  - name: orgs-usage
outputs:
  - name: orgs-usage-consolidated

run:
  path: sh
  args:
  - -exc
  - |
    ls -l *
    rm -rf ./orgs-usage-consolidated/2*.json
    node ./pipeline-scripts/scripts/consolidate-usage-data.js
    export datetimePrefix=$(date +%Y%m%d_%H%M_)
    cp -f $(ls -t -1 ./orgs-usage-consolidated/*.json | head -1) ./orgs-usage-consolidated/${datetimePrefix}report.json
    cp -f ./orgs-usage-consolidated/${datetimePrefix}report.json ./orgs-usage-consolidated/report.json
    ls -l *
