---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/pcf-usage-tools
    tag: "latest"

inputs:
  - name: pipeline-scripts
  - name: report-time-range
  - name: orgs-usage
outputs:
  - name: orgs-usage-consolidated

run:
  path: sh
  args:
  - -exc
  - |
    node ./pipeline-scripts/scripts/consolidate-usage-data.js
    ls -la ./orgs-usage-consolidated
    cat `ls ./orgs-usage-consolidated/*.json`
