---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/pcf-usage-tools
    tag: "latest"

inputs:
  - name: orgs-usage-consolidated
outputs:
  - name: orgs-usage-consolidated

run:
  path: sh
  args:
  - -exc
  - |
    cat ./orgs-usage-consolidated/report.json
