---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: everpeace/curl-jq
    tag: "latest"

inputs:
  - name: orgs-usage-consolidated
outputs:
  - name: orgs-usage-filtered

run:
  path: ci/tasks/filter-usage-data.sh 
