---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/pcf-usage-tools
    tag: "latest"

inputs:
  - name: orgs-usage-consolidated
  - name: pipeline-scripts
outputs:
  - name: orgs-usage-filtered

run:
  path: ./pipeline-scripts/ci/tasks/filter-usage-data.sh

