---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/pcf-usage-tools
    tag: "latest"

inputs:
  - name: pipeline-scripts
  - name: report-time-range
outputs:
  - name: orgs-usage

run:
  path: ls
  # args:
  # - -exc
  # - |
  #   node pipeline-scripts/scripts/get-usage-data.js
