---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/pcf-usage-tools
    tag: "latest"

inputs:
  - name: pipeline-scripts
  - name: report-time-range
outputs:
  - name: orgs-usage

run:
  path: sh
  args:
  - -exc
  - |
    ls -l *
    rm -f ./orgs-usage/pcf-orgs-usage.json
    node pipeline-scripts/scripts/get-usage-data.js
    ls -l *
    export datetimePrefix=$(date +%Y%m%d_%H%M_)
    cp -f ./orgs-usage/pcf-orgs-usage.json ./orgs-usage/${datetimePrefix}pcf-orgs-usage.json
    ls -l *
